# Generated by Django 3.0.6 on 2020-06-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beer',
            options={'verbose_name': 'beer', 'verbose_name_plural': 'beers'},
        ),
        migrations.AlterField(
            model_name='beer',
            name='product_name',
            field=models.CharField(max_length=140),
        ),
    ]
