# Generated by Django 3.0.6 on 2020-06-16 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payingorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='payingorder',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orders.Order'),
            preserve_default=False,
        ),
    ]
